version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - "8140:8140"
    volumes:
      - ./code:/etc/puppetlabs/code/
      - ./puppet:/etc/puppetlabs/puppet/
      - ./puppetssl:/etc/puppetlabs/puppet/ssl/
      - ./serverdata:/opt/puppetlabs/server/data/puppetserver/
      - ./modules:/etc/puppetlabs/code/modules
    networks:
      - tools

  puppetdb-postgres:
    container_name: postgres
    hostname: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - ./puppetdb-postgres/data:/var/lib/postgresql/data/
    networks:
      - tools

  puppetdb:
    hostname: puppetdb
    container_name: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081
    volumes:
      - ./puppetssl:/etc/puppetlabs/puppet/ssl/
    networks:
      - tools

networks:
  tools:
